### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by 417-72KI**

### CODE REVIEW

**Comment by 417-72KI** [comment]
@jagreenwood 
I'm not sure where it's happening, but maybe.

**Comment by jagreenwood** [comment]
@417-72KI I'm still seeing an error. Looks like the action is pulling the 5.9.2 docker image.

Screenshot 2024-07-24 at 2 34 46 PM

This is my workflow config

```yaml
name: Run Danger
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  build:
    if: github.event.pull_request.draft == false
    name: "Run Danger"
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Danger
        uses: 417-72KI/danger-swiftlint@v5.10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by jagreenwood** [comment]
Oh maybe because 5.9 in action.yml

**Comment by 417-72KI** [comment]
@jagreenwood 
Thank you for finding the reason and sorry for inconvinience.
I'm going to fix it now🤦‍♂️

**Pull request merged**
